"""Add Jira VOC scoring tables

Revision ID: cc0ac6d9f1e4
Revises: 005_add_competitive_intelligence
Create Date: 2025-11-18 04:49:11.433862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'cc0ac6d9f1e4'
down_revision: Union[str, None] = '005_add_competitive_intelligence'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jira_key', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'DONE', 'CLOSED', 'BACKLOG', name='jiraticketstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOWEST', 'LOW', 'MEDIUM', 'HIGH', 'HIGHEST', name='jiraticketpriority'), nullable=False),
    sa.Column('embedding', Vector(384), nullable=True),
    sa.Column('assignee', sa.String(length=255), nullable=True),
    sa.Column('reporter', sa.String(length=255), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('epic_key', sa.String(length=50), nullable=True),
    sa.Column('story_points', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('jira_created_at', sa.DateTime(), nullable=True),
    sa.Column('jira_updated_at', sa.DateTime(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jira_tickets_jira_key'), 'jira_tickets', ['jira_key'], unique=True)
    op.create_table('voc_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('customer_count', sa.Integer(), nullable=False),
    sa.Column('total_acv', sa.Float(), nullable=False),
    sa.Column('feedback_volume', sa.Integer(), nullable=False),
    sa.Column('ent_customer_count', sa.Integer(), nullable=False),
    sa.Column('mm_customer_count', sa.Integer(), nullable=False),
    sa.Column('smb_customer_count', sa.Integer(), nullable=False),
    sa.Column('customer_score', sa.Float(), nullable=False),
    sa.Column('acv_score', sa.Float(), nullable=False),
    sa.Column('segment_score', sa.Float(), nullable=False),
    sa.Column('volume_score', sa.Float(), nullable=False),
    sa.Column('voc_score', sa.Float(), nullable=False),
    sa.Column('recommended_priority', sa.String(length=20), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['jira_tickets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id')
    )
    op.create_index(op.f('ix_voc_scores_voc_score'), 'voc_scores', ['voc_score'], unique=False)
    op.create_table('jira_insight_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('insight_id', sa.UUID(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('is_confirmed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['jira_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('artifacts_external_id_key', 'artifacts', type_='unique')
    op.drop_index('ix_competitive_metadata_competitor', table_name='competitive_insight_metadata')
    op.drop_index('ix_competitive_metadata_insight_id', table_name='competitive_insight_metadata')
    op.drop_index('ix_competitive_metadata_session', table_name='competitive_insight_metadata')
    op.drop_index('ix_competitors_name', table_name='competitors')
    op.drop_index('ix_competitors_status', table_name='competitors')
    op.drop_constraint('customers_name_key', 'customers', type_='unique')
    op.drop_index('idx_feedback_embedding', table_name='feedback', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index('idx_feedback_text_fts', table_name='feedback', postgresql_using='gin')
    op.drop_index('ix_insight_feedback_feedback_id', table_name='insight_feedback')
    op.drop_index('ix_insight_feedback_insight_id', table_name='insight_feedback')
    op.drop_constraint('insight_feedback_insight_id_fkey', 'insight_feedback', type_='foreignkey')
    op.drop_constraint('insight_feedback_feedback_id_fkey', 'insight_feedback', type_='foreignkey')
    op.create_foreign_key(None, 'insight_feedback', 'insights', ['insight_id'], ['id'])
    op.create_foreign_key(None, 'insight_feedback', 'feedback', ['feedback_id'], ['id'])
    op.drop_index('ix_insights_priority_score', table_name='insights')
    op.drop_index('ix_research_sessions_company', table_name='research_sessions')
    op.drop_index('ix_research_sessions_status', table_name='research_sessions')
    op.drop_index('idx_themes_centroid', table_name='themes', postgresql_with={'lists': '50'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_themes_centroid', 'themes', ['centroid'], unique=False, postgresql_with={'lists': '50'}, postgresql_using='ivfflat')
    op.create_index('ix_research_sessions_status', 'research_sessions', ['status'], unique=False)
    op.create_index('ix_research_sessions_company', 'research_sessions', ['company_name'], unique=False)
    op.create_index('ix_insights_priority_score', 'insights', ['priority_score'], unique=False)
    op.drop_constraint(None, 'insight_feedback', type_='foreignkey')
    op.drop_constraint(None, 'insight_feedback', type_='foreignkey')
    op.create_foreign_key('insight_feedback_feedback_id_fkey', 'insight_feedback', 'feedback', ['feedback_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('insight_feedback_insight_id_fkey', 'insight_feedback', 'insights', ['insight_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_insight_feedback_insight_id', 'insight_feedback', ['insight_id'], unique=False)
    op.create_index('ix_insight_feedback_feedback_id', 'insight_feedback', ['feedback_id'], unique=False)
    op.create_index('idx_feedback_text_fts', 'feedback', [sa.text("to_tsvector('english'::regconfig, text)")], unique=False, postgresql_using='gin')
    op.create_index('idx_feedback_embedding', 'feedback', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_unique_constraint('customers_name_key', 'customers', ['name'])
    op.create_index('ix_competitors_status', 'competitors', ['status'], unique=False)
    op.create_index('ix_competitors_name', 'competitors', ['name'], unique=False)
    op.create_index('ix_competitive_metadata_session', 'competitive_insight_metadata', ['research_session_id'], unique=False)
    op.create_index('ix_competitive_metadata_insight_id', 'competitive_insight_metadata', ['insight_id'], unique=False)
    op.create_index('ix_competitive_metadata_competitor', 'competitive_insight_metadata', ['competitor_name'], unique=False)
    op.create_unique_constraint('artifacts_external_id_key', 'artifacts', ['external_id'])
    op.drop_table('jira_insight_matches')
    op.drop_index(op.f('ix_voc_scores_voc_score'), table_name='voc_scores')
    op.drop_table('voc_scores')
    op.drop_index(op.f('ix_jira_tickets_jira_key'), table_name='jira_tickets')
    op.drop_table('jira_tickets')
    # ### end Alembic commands ###
